/*
 * PropagatorPanel.java
 * =====================================================================
 *   This file is part of JSatTrak.
 *
 *   Copyright 2007-2013 Shawn E. Gano
 *   
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *   
 *       http://www.apache.org/licenses/LICENSE-2.0
 *   
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 * =====================================================================
 *
 * Created on January 14, 2008, 2:54 PM
 */

package jsattrak.customsat.gui;

import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

import jsattrak.customsat.InitialConditionsNode;
import jsattrak.customsat.PropagatorNode;

/**
 * 
 * @author sgano
 */
public class PropagatorPanel extends javax.swing.JPanel {

	private static final long serialVersionUID = 3532395304593969598L;
	
	PropagatorNode pNode;
	private JInternalFrame iframe; // used to know what its parent frame is - to
									// close window

	/** Creates new form PropogatorPanel */
	public PropagatorPanel(PropagatorNode pNode, JInternalFrame iframe) {
		this.pNode = pNode;
		this.iframe = iframe;

		initComponents();

		// If initials conditions are TLE's
		if (pNode.getInitNode().getCoordinate() == InitialConditionsNode.TLE) {
			propTabbedPane.setSelectedIndex(PropagatorNode.TLE);

			// Disable others tabs
			for (int i = 0; i <= 3; i++) {
				propTabbedPane.setEnabledAt(i, false);
			}

		}

		// Reload the panel with good propogator
		else if (pNode.getPropogator() != PropagatorNode.TLE) {

			propTabbedPane.setSelectedIndex(pNode.getPropogator());
			// Disable TLE tab
			propTabbedPane.setEnabledAt(PropagatorNode.TLE, false);
		}
		// If the user has changed initials conditions from TLE to others
		else {
			propTabbedPane.setSelectedIndex(PropagatorNode.NUMERICAL);
			// Disable TLE tab
			propTabbedPane.setEnabledAt(PropagatorNode.TLE, false);
		}

		// fill in fields with saved values
		jSpinner1.setValue(pNode.getN_max());
		jSpinner2.setValue(pNode.getM_max());

		jCheckBox1.setSelected(pNode.isIncludeLunarPert());
		jCheckBox2.setSelected(pNode.isIncludeSunPert());
		jCheckBox3.setSelected(pNode.isIncludeSolRadPress());
		jCheckBox4.setSelected(pNode.isIncludeAtmosDrag());

		jTextField1.setText("" + pNode.getMass());
		jTextField2.setText("" + pNode.getArea());
		jTextField3.setText("" + pNode.getCR());
		jTextField4.setText("" + pNode.getCD());

		jTextField5.setText("" + pNode.getStepSize());

		// Hprop-7/8
		jTextField6.setText("" + pNode.getMaxStepSize());
		jTextField7.setText("" + pNode.getMinStepSize());
		jTextField8.setText("" + pNode.getRelAccuracy());

		// Keplerian
		jTextField10.setText("" + pNode.getMu());
		// Eckstein Hechler
		jTextField11.setText("" + pNode.getMu());

		// Un-normalized zonal coefficient

		double[] zonalCoefficients = pNode.getZonalCoefficients();

		jTextField12.setText("" + zonalCoefficients[0]);
		jTextField13.setText("" + zonalCoefficients[1]);
		jTextField14.setText("" + zonalCoefficients[2]);
		jTextField15.setText("" + zonalCoefficients[3]);
		jTextField16.setText("" + zonalCoefficients[4]);

		// prop len
		jTextField9.setText("" + pNode.getPopogateTimeLen());

		// stoppping conditions
		perigeeCheckBox.setSelected(pNode.isStopOnPerigee());
		apogeeCheckBox.setSelected(pNode.isStopOnApogee());

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		propTabbedPane = new javax.swing.JTabbedPane();
		jPanel1 = new javax.swing.JPanel();
		jPanel3 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jSpinner1 = new javax.swing.JSpinner();
		jLabel3 = new javax.swing.JLabel();
		jSpinner2 = new javax.swing.JSpinner();
		jPanel5 = new javax.swing.JPanel();
		jCheckBox1 = new javax.swing.JCheckBox();
		jCheckBox2 = new javax.swing.JCheckBox();
		jCheckBox4 = new javax.swing.JCheckBox();
		jCheckBox3 = new javax.swing.JCheckBox();
		jPanel7 = new javax.swing.JPanel();
		jLabel12 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jTextField6 = new javax.swing.JTextField();
		jTextField7 = new javax.swing.JTextField();
		jTextField8 = new javax.swing.JTextField();
		jPanel4 = new javax.swing.JPanel();
		jLabel4 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		jTextField2 = new javax.swing.JTextField();
		jLabel7 = new javax.swing.JLabel();
		jTextField4 = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		jTextField3 = new javax.swing.JTextField();
		jPanel11 = new javax.swing.JPanel();
		jPanel13 = new javax.swing.JPanel();
		jLabel13 = new javax.swing.JLabel();
		jTextField10 = new javax.swing.JTextField();
		jPanel12 = new javax.swing.JPanel();
		jPanel9 = new javax.swing.JPanel();
		jLabel14 = new javax.swing.JLabel();
		jTextField11 = new javax.swing.JTextField();
		jPanel2 = new javax.swing.JPanel();
		jLabel15 = new javax.swing.JLabel();
		jLabel16 = new javax.swing.JLabel();
		jLabel17 = new javax.swing.JLabel();
		jLabel18 = new javax.swing.JLabel();
		jLabel19 = new javax.swing.JLabel();
		jTextField12 = new javax.swing.JTextField();
		jTextField13 = new javax.swing.JTextField();
		jTextField14 = new javax.swing.JTextField();
		jTextField15 = new javax.swing.JTextField();
		jTextField16 = new javax.swing.JTextField();
		jPanel8 = new javax.swing.JPanel();
		perigeeCheckBox = new javax.swing.JCheckBox();
		apogeeCheckBox = new javax.swing.JCheckBox();
		jPanel10 = new javax.swing.JPanel();
		jPanel14 = new javax.swing.JPanel();
		jPanel6 = new javax.swing.JPanel();
		jLabel8 = new javax.swing.JLabel();
		jTextField5 = new javax.swing.JTextField();
		jLabel9 = new javax.swing.JLabel();
		jTextField9 = new javax.swing.JTextField();
		okButton = new javax.swing.JButton();
		applyButton = new javax.swing.JButton();
		cancelButton = new javax.swing.JButton();

		propTabbedPane.setMinimumSize(new java.awt.Dimension(0, 0));
		propTabbedPane.setOpaque(true);
		propTabbedPane.setPreferredSize(new java.awt.Dimension(0, 0));

		jPanel1.setMinimumSize(new java.awt.Dimension(414, 394));
		jPanel1.setPreferredSize(new java.awt.Dimension(0, 0));

		jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null,
				"Gravity Model", javax.swing.border.TitledBorder.LEADING,
				javax.swing.border.TitledBorder.DEFAULT_POSITION));
		jPanel3.setMaximumSize(new java.awt.Dimension(32777, 32790));
		jPanel3.setMinimumSize(new java.awt.Dimension(414, 55));
		jPanel3.setPreferredSize(new java.awt.Dimension(418, 55));

		jLabel2.setText("Gravity Model Degree:");
		jLabel2.setMaximumSize(new java.awt.Dimension(123, 16));
		jLabel2.setMinimumSize(new java.awt.Dimension(123, 16));
		jLabel2.setPreferredSize(new java.awt.Dimension(123, 16));

		jSpinner1.setMinimumSize(new java.awt.Dimension(42, 20));
		jSpinner1.setPreferredSize(new java.awt.Dimension(42, 20));
		jSpinner1.setVerifyInputWhenFocusTarget(false);

		jLabel3.setText("Gravity Model Order:");
		jLabel3.setMaximumSize(new java.awt.Dimension(115, 16));
		jLabel3.setMinimumSize(new java.awt.Dimension(115, 16));
		jLabel3.setPreferredSize(new java.awt.Dimension(115, 16));

		jSpinner2.setMinimumSize(new java.awt.Dimension(42, 20));
		jSpinner2.setPreferredSize(new java.awt.Dimension(42, 20));

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout
				.setHorizontalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addGap(21, 21, 21)
										.addComponent(
												jLabel2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												jSpinner1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addComponent(
												jLabel3,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(5, 5, 5)
										.addComponent(
												jSpinner2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)));
		jPanel3Layout
				.setVerticalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addGap(5,
																				5,
																				5)
																		.addComponent(
																				jSpinner2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addGap(5,
																				5,
																				5)
																		.addGroup(
																				jPanel3Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel3Layout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.BASELINE)
																										.addComponent(
																												jLabel2,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addComponent(
																												jSpinner1,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addComponent(
																								jLabel3,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE))))
										.addGap(9, 9, 9)));

		jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null,
				"Propagator External Force Options:",
				javax.swing.border.TitledBorder.LEADING,
				javax.swing.border.TitledBorder.DEFAULT_POSITION));
		jPanel5.setMaximumSize(new java.awt.Dimension(32777, 32790));
		jPanel5.setMinimumSize(new java.awt.Dimension(353, 71));
		jPanel5.setPreferredSize(new java.awt.Dimension(415, 71));

		jCheckBox1.setText("Lunar Perturbations");
		jCheckBox1.setMaximumSize(new java.awt.Dimension(139, 24));
		jCheckBox1.setMinimumSize(new java.awt.Dimension(139, 24));
		jCheckBox1.setPreferredSize(new java.awt.Dimension(139, 24));

		jCheckBox2.setText("Solar Perturbations");
		jCheckBox2.setMaximumSize(new java.awt.Dimension(136, 24));
		jCheckBox2.setMinimumSize(new java.awt.Dimension(136, 24));
		jCheckBox2.setPreferredSize(new java.awt.Dimension(136, 24));

		jCheckBox4.setText("Atmospheric Drag");
		jCheckBox4.setMaximumSize(new java.awt.Dimension(128, 24));
		jCheckBox4.setMinimumSize(new java.awt.Dimension(128, 24));
		jCheckBox4.setPreferredSize(new java.awt.Dimension(128, 24));

		jCheckBox3.setText("Solar Radiation Pressure");
		jCheckBox3.setMaximumSize(new java.awt.Dimension(167, 24));
		jCheckBox3.setMinimumSize(new java.awt.Dimension(167, 24));
		jCheckBox3.setPreferredSize(new java.awt.Dimension(167, 24));

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(
				jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout
				.setHorizontalGroup(jPanel5Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel5Layout
										.createSequentialGroup()
										.addGap(41, 41, 41)
										.addGroup(
												jPanel5Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(
																jCheckBox1,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																jCheckBox4,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addGap(26, 26, 26)
										.addGroup(
												jPanel5Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jCheckBox2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jCheckBox3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																146,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));
		jPanel5Layout
				.setVerticalGroup(jPanel5Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel5Layout
										.createSequentialGroup()
										.addGap(5, 5, 5)
										.addGroup(
												jPanel5Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jCheckBox2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jCheckBox1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(5, 5, 5)
										.addGroup(
												jPanel5Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jCheckBox3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jCheckBox4,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null,
				"Adaptive Step Size Settings",
				javax.swing.border.TitledBorder.LEADING,
				javax.swing.border.TitledBorder.DEFAULT_POSITION));
		jPanel7.setMaximumSize(new java.awt.Dimension(32777, 95));
		jPanel7.setMinimumSize(new java.awt.Dimension(273, 95));
		jPanel7.setPreferredSize(new java.awt.Dimension(390, 95));

		jLabel12.setText("dP [m]:");
		jLabel12.setMaximumSize(new java.awt.Dimension(40, 16));
		jLabel12.setMinimumSize(new java.awt.Dimension(40, 16));
		jLabel12.setPreferredSize(new java.awt.Dimension(40, 16));

		jLabel11.setText("Min Step Size [s]:");
		jLabel11.setMaximumSize(new java.awt.Dimension(97, 16));
		jLabel11.setMinimumSize(new java.awt.Dimension(97, 16));
		jLabel11.setPreferredSize(new java.awt.Dimension(97, 16));

		jLabel10.setText("Max Step Size [s]:");
		jLabel10.setMaximumSize(new java.awt.Dimension(101, 16));
		jLabel10.setMinimumSize(new java.awt.Dimension(101, 16));
		jLabel10.setPreferredSize(new java.awt.Dimension(101, 16));

		javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(
				jPanel7);
		jPanel7.setLayout(jPanel7Layout);
		jPanel7Layout
				.setHorizontalGroup(jPanel7Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel7Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel7Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel7Layout
																		.createSequentialGroup()
																		.addGap(23,
																				23,
																				23)
																		.addComponent(
																				jLabel12,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addComponent(
																jLabel11,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel7Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel7Layout
																		.createSequentialGroup()
																		.addComponent(
																				jTextField7,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				64,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(26,
																				26,
																				26)
																		.addComponent(
																				jLabel10,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jTextField6,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				64,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addComponent(
																jTextField8,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																64,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(32, Short.MAX_VALUE)));
		jPanel7Layout
				.setVerticalGroup(jPanel7Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel7Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel7Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel7Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(
																				jLabel10,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				jTextField6,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel7Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(
																				jLabel11,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				jTextField7,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												jPanel7Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jLabel12,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField8,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null,
				"Spacecraft Properties",
				javax.swing.border.TitledBorder.LEADING,
				javax.swing.border.TitledBorder.DEFAULT_POSITION));
		jPanel4.setMaximumSize(new java.awt.Dimension(32777, 81));
		jPanel4.setMinimumSize(new java.awt.Dimension(346, 81));
		jPanel4.setPreferredSize(new java.awt.Dimension(438, 81));

		jLabel4.setText("Spacecraft Mass [kg]:");
		jLabel4.setMaximumSize(new java.awt.Dimension(125, 16));
		jLabel4.setMinimumSize(new java.awt.Dimension(125, 16));
		jLabel4.setPreferredSize(new java.awt.Dimension(125, 16));

		jLabel5.setText("Cross-section Area [m^2]:");
		jLabel5.setMaximumSize(new java.awt.Dimension(149, 16));
		jLabel5.setMinimumSize(new java.awt.Dimension(149, 16));
		jLabel5.setPreferredSize(new java.awt.Dimension(149, 16));

		jTextField2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField2ActionPerformed(evt);
			}
		});

		jLabel7.setText("Drag Coefficient:");
		jLabel7.setMaximumSize(new java.awt.Dimension(94, 16));
		jLabel7.setMinimumSize(new java.awt.Dimension(94, 16));
		jLabel7.setPreferredSize(new java.awt.Dimension(94, 16));

		jLabel6.setText("Solar Rad Pressure Coef:");
		jLabel6.setMaximumSize(new java.awt.Dimension(143, 16));
		jLabel6.setMinimumSize(new java.awt.Dimension(143, 16));
		jLabel6.setPreferredSize(new java.awt.Dimension(143, 16));

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(
				jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout
				.setHorizontalGroup(jPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel4Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jLabel7,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jLabel4,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																107,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(
																jTextField1,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																48,
																Short.MAX_VALUE)
														.addComponent(
																jTextField4))
										.addGap(18, 18, 18)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jLabel6,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																135,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jLabel5,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(
																jTextField2,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																58,
																Short.MAX_VALUE)
														.addComponent(
																jTextField3))
										.addContainerGap()));
		jPanel4Layout
				.setVerticalGroup(jPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel4Layout
										.createSequentialGroup()
										.addGap(5, 5, 5)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel4Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(
																				jTextField2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				jLabel5,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel4Layout
																		.createSequentialGroup()
																		.addGap(2,
																				2,
																				2)
																		.addGroup(
																				jPanel4Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel4,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jTextField1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE))))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jLabel7,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField4,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jLabel6,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING,
																				false)
																		.addComponent(
																				jPanel3,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addComponent(
																				jPanel5,
																				javax.swing.GroupLayout.Alignment.LEADING,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				418,
																				Short.MAX_VALUE)
																		.addComponent(
																				jPanel7,
																				javax.swing.GroupLayout.Alignment.LEADING,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				418,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addComponent(
																jPanel4,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																418,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(17, Short.MAX_VALUE)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												jPanel3,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												52,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(5, 5, 5)
										.addComponent(
												jPanel5,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												82,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jPanel7,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												88,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jPanel4,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(63, Short.MAX_VALUE)));

		propTabbedPane.addTab("Numerical", jPanel1);

		jPanel11.setMaximumSize(new java.awt.Dimension(32777, 43));
		jPanel11.setMinimumSize(new java.awt.Dimension(189, 43));
		jPanel11.setPreferredSize(new java.awt.Dimension(306, 43));

		jPanel13.setBorder(javax.swing.BorderFactory
				.createTitledBorder("Central attraction coefficient"));

		jLabel13.setText("Mu :");
		jLabel13.setMaximumSize(new java.awt.Dimension(17, 16));
		jLabel13.setMinimumSize(new java.awt.Dimension(17, 16));
		jLabel13.setPreferredSize(new java.awt.Dimension(17, 16));

		javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(
				jPanel13);
		jPanel13.setLayout(jPanel13Layout);
		jPanel13Layout
				.setHorizontalGroup(jPanel13Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel13Layout
										.createSequentialGroup()
										.addContainerGap(112, Short.MAX_VALUE)
										.addComponent(
												jLabel13,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												26,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												jTextField10,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												159,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(102, 102, 102)));
		jPanel13Layout
				.setVerticalGroup(jPanel13Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel13Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel13Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jTextField10,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jLabel13,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addContainerGap(19, Short.MAX_VALUE)));

		javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(
				jPanel11);
		jPanel11.setLayout(jPanel11Layout);
		jPanel11Layout.setHorizontalGroup(jPanel11Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel11Layout
						.createSequentialGroup()
						.addContainerGap()
						.addComponent(jPanel13,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE).addContainerGap()));
		jPanel11Layout.setVerticalGroup(jPanel11Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel11Layout
						.createSequentialGroup()
						.addContainerGap()
						.addComponent(jPanel13,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(249, Short.MAX_VALUE)));

		propTabbedPane.addTab("Keplerian", jPanel11);

		jPanel12.setMaximumSize(new java.awt.Dimension(32767, 581));
		jPanel12.setMinimumSize(new java.awt.Dimension(199, 581));
		jPanel12.setPreferredSize(new java.awt.Dimension(401, 581));

		jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null,
				"Central attraction coefficient",
				javax.swing.border.TitledBorder.LEADING,
				javax.swing.border.TitledBorder.DEFAULT_POSITION));
		jPanel9.setMaximumSize(new java.awt.Dimension(32777, 43));
		jPanel9.setMinimumSize(new java.awt.Dimension(189, 43));
		jPanel9.setPreferredSize(new java.awt.Dimension(306, 43));

		jLabel14.setText("Mu");
		jLabel14.setMaximumSize(new java.awt.Dimension(17, 16));
		jLabel14.setMinimumSize(new java.awt.Dimension(17, 16));
		jLabel14.setPreferredSize(new java.awt.Dimension(17, 16));

		javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(
				jPanel9);
		jPanel9.setLayout(jPanel9Layout);
		jPanel9Layout.setHorizontalGroup(jPanel9Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel9Layout
						.createSequentialGroup()
						.addGap(61, 61, 61)
						.addComponent(jLabel14,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(jTextField11,
								javax.swing.GroupLayout.PREFERRED_SIZE, 165,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));
		jPanel9Layout
				.setVerticalGroup(jPanel9Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel9Layout
										.createSequentialGroup()
										.addGroup(
												jPanel9Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jTextField11)
														.addComponent(
																jLabel14,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap()));

		jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null,
				"Un-normalized zonal coefficient",
				javax.swing.border.TitledBorder.LEADING,
				javax.swing.border.TitledBorder.DEFAULT_POSITION));
		jPanel2.setMaximumSize(new java.awt.Dimension(32777, 147));
		jPanel2.setMinimumSize(new java.awt.Dimension(194, 147));
		jPanel2.setPreferredSize(new java.awt.Dimension(311, 147));

		jLabel15.setText("C20");
		jLabel15.setMaximumSize(new java.awt.Dimension(22, 16));
		jLabel15.setMinimumSize(new java.awt.Dimension(22, 16));
		jLabel15.setPreferredSize(new java.awt.Dimension(22, 16));

		jLabel16.setText("C30");
		jLabel16.setMaximumSize(new java.awt.Dimension(22, 16));
		jLabel16.setMinimumSize(new java.awt.Dimension(22, 16));
		jLabel16.setPreferredSize(new java.awt.Dimension(22, 16));

		jLabel17.setText("C40");
		jLabel17.setMaximumSize(new java.awt.Dimension(22, 16));
		jLabel17.setMinimumSize(new java.awt.Dimension(22, 16));
		jLabel17.setPreferredSize(new java.awt.Dimension(22, 16));

		jLabel18.setText("C50");
		jLabel18.setMaximumSize(new java.awt.Dimension(22, 16));
		jLabel18.setMinimumSize(new java.awt.Dimension(22, 16));
		jLabel18.setPreferredSize(new java.awt.Dimension(22, 16));

		jLabel19.setText("C60");
		jLabel19.setMaximumSize(new java.awt.Dimension(22, 16));
		jLabel19.setMinimumSize(new java.awt.Dimension(22, 16));
		jLabel19.setPreferredSize(new java.awt.Dimension(22, 16));

		jTextField13.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField13ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addGap(117, 117, 117)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																jPanel2Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel19,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(18,
																				18,
																				18)
																		.addComponent(
																				jTextField16))
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel18,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(18,
																				18,
																				18)
																		.addComponent(
																				jTextField15))
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel17,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(18,
																				18,
																				18)
																		.addComponent(
																				jTextField14))
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel16,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(18,
																				18,
																				18)
																		.addComponent(
																				jTextField13))
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addGap(0,
																				0,
																				Short.MAX_VALUE)
																		.addComponent(
																				jLabel15,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(18,
																				18,
																				18)
																		.addComponent(
																				jTextField12,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				100,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGap(111, 111, 111)));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jLabel15,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField12,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jLabel16,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField13,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jLabel17,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField14,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jLabel18,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField15,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jLabel19,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField16,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(19, Short.MAX_VALUE)));

		jPanel8.setMinimumSize(new java.awt.Dimension(199, 64));
		jPanel8.setPreferredSize(new java.awt.Dimension(401, 299));

		perigeeCheckBox.setText("Stop propagating at Perigee");
		perigeeCheckBox.setMaximumSize(new java.awt.Dimension(183, 24));
		perigeeCheckBox.setMinimumSize(new java.awt.Dimension(183, 24));
		perigeeCheckBox.setPreferredSize(new java.awt.Dimension(183, 24));
		jPanel8.add(perigeeCheckBox);

		apogeeCheckBox.setText("Stop propagating at Apogee");
		apogeeCheckBox.setMinimumSize(new java.awt.Dimension(182, 24));
		apogeeCheckBox.setPreferredSize(new java.awt.Dimension(182, 24));
		apogeeCheckBox.setMaximumSize(new java.awt.Dimension(182, 24));
		jPanel8.add(apogeeCheckBox);

		javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(
				jPanel12);
		jPanel12.setLayout(jPanel12Layout);
		jPanel12Layout
				.setHorizontalGroup(jPanel12Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel12Layout
										.createSequentialGroup()
										.addGroup(
												jPanel12Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																jPanel12Layout
																		.createSequentialGroup()
																		.addGap(25,
																				25,
																				25)
																		.addComponent(
																				jPanel8,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				384,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel12Layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addGroup(
																				jPanel12Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								jPanel2,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								384,
																								Short.MAX_VALUE)
																						.addComponent(
																								jPanel9,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								384,
																								Short.MAX_VALUE))))
										.addContainerGap()));
		jPanel12Layout
				.setVerticalGroup(jPanel12Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel12Layout
										.createSequentialGroup()
										.addGap(13, 13, 13)
										.addComponent(
												jPanel9,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												50,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												jPanel2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												178,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												jPanel8,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												38,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap()));

		propTabbedPane.addTab("Eckstein Hechler", jPanel12);

		jPanel10.setMinimumSize(new java.awt.Dimension(0, 0));
		jPanel10.setPreferredSize(new java.awt.Dimension(210, 243));
		propTabbedPane.addTab("Semi-Analytical", jPanel10);

		jPanel14.setMinimumSize(new java.awt.Dimension(0, 0));
		jPanel14.setPreferredSize(new java.awt.Dimension(210, 243));
		propTabbedPane.addTab("TLE", jPanel14);

		jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null,
				"Display Settings", javax.swing.border.TitledBorder.LEADING,
				javax.swing.border.TitledBorder.DEFAULT_POSITION));
		jPanel6.setMaximumSize(new java.awt.Dimension(32777, 32790));
		jPanel6.setMinimumSize(new java.awt.Dimension(299, 55));
		jPanel6.setPreferredSize(new java.awt.Dimension(415, 55));

		jLabel8.setText("Step Size [s]:");
		jLabel8.setMaximumSize(new java.awt.Dimension(74, 16));
		jLabel8.setMinimumSize(new java.awt.Dimension(74, 16));
		jLabel8.setPreferredSize(new java.awt.Dimension(74, 16));

		jLabel9.setText("Duration [s]:");
		jLabel9.setMaximumSize(new java.awt.Dimension(69, 16));
		jLabel9.setMinimumSize(new java.awt.Dimension(69, 16));
		jLabel9.setPreferredSize(new java.awt.Dimension(69, 16));

		jTextField9.setToolTipText("How long to propogate satellite");

		javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(
				jPanel6);
		jPanel6.setLayout(jPanel6Layout);
		jPanel6Layout
				.setHorizontalGroup(jPanel6Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel6Layout
										.createSequentialGroup()
										.addGap(21, 21, 21)
										.addComponent(
												jLabel8,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jTextField5,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												80,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(42, 42, 42)
										.addComponent(
												jLabel9,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												jTextField9,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												80,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));
		jPanel6Layout
				.setVerticalGroup(jPanel6Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel6Layout
										.createSequentialGroup()
										.addGap(5, 5, 5)
										.addGroup(
												jPanel6Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jTextField5,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jLabel8,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jLabel9,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField9,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(9, 9, 9)));

		okButton.setText("Ok");
		okButton.setMaximumSize(new java.awt.Dimension(50, 26));
		okButton.setMinimumSize(new java.awt.Dimension(50, 26));
		okButton.setPreferredSize(new java.awt.Dimension(50, 26));
		okButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				okButtonActionPerformed(evt);
			}
		});

		applyButton.setText("Apply");
		applyButton.setMaximumSize(new java.awt.Dimension(65, 26));
		applyButton.setMinimumSize(new java.awt.Dimension(65, 26));
		applyButton.setPreferredSize(new java.awt.Dimension(65, 26));
		applyButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				applyButtonActionPerformed(evt);
			}
		});

		cancelButton.setText("Cancel");
		cancelButton.setMaximumSize(new java.awt.Dimension(73, 26));
		cancelButton.setMinimumSize(new java.awt.Dimension(73, 26));
		cancelButton.setPreferredSize(new java.awt.Dimension(73, 26));
		cancelButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cancelButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										okButton,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										63,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																								.addComponent(
																										applyButton,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																								.addComponent(
																										cancelButton,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										javax.swing.GroupLayout.PREFERRED_SIZE))
																				.addComponent(
																						propTabbedPane,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						450,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGap(0,
																		0,
																		Short.MAX_VALUE))
												.addComponent(
														jPanel6,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														450, Short.MAX_VALUE))
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(propTabbedPane,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										362,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jPanel6,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														okButton,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														applyButton,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														cancelButton,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));
	}// </editor-fold>//GEN-END:initComponents

	// private void inputComboBoxActionPerformed(java.awt.event.ActionEvent
	// evt)//GEN-FIRST:event_inputComboBoxActionPerformed
	// {//GEN-HEADEREND:event_inputComboBoxActionPerformed
	// if(inputComboBox.getSelectedIndex() <= 1) // 0 or 1, Hprop 4 or 8
	// {
	// propTabbedPane.setEnabledAt(0, true); // kep
	// propTabbedPane.setEnabledAt(1, false); // j2k
	// propTabbedPane.setSelectedIndex(0);
	//
	// }
	// else if(inputComboBox.getSelectedIndex() == 2) // Hprop 7-8, adaptive
	// {
	// propTabbedPane.setEnabledAt(0, true); // kep
	// propTabbedPane.setEnabledAt(1, true);
	// propTabbedPane.setSelectedIndex(1);
	//
	// }
	// }//GEN-LAST:event_inputComboBoxActionPerformed

	private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField2ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField2ActionPerformed

	private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField13ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField13ActionPerformed

	private void okButtonActionPerformed(java.awt.event.ActionEvent evt)// GEN-FIRST:event_okButtonActionPerformed
	{// GEN-HEADEREND:event_okButtonActionPerformed
		boolean success = saveSettings();

		// close internal frame
		if (success) {
			try {
				iframe.dispose(); // could setClosed(true)
			} catch (Exception e) {
			}
		}
	}// GEN-LAST:event_okButtonActionPerformed

	private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt)// GEN-FIRST:event_cancelButtonActionPerformed
	{// GEN-HEADEREND:event_cancelButtonActionPerformed
		// close internal frame
		try {
			iframe.dispose(); // could setClosed(true)
		} catch (Exception e) {
		}
	}// GEN-LAST:event_cancelButtonActionPerformed

	private void applyButtonActionPerformed(java.awt.event.ActionEvent evt)// GEN-FIRST:event_applyButtonActionPerformed
	{// GEN-HEADEREND:event_applyButtonActionPerformed
		saveSettings();
	}// GEN-LAST:event_applyButtonActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JCheckBox apogeeCheckBox;
	private javax.swing.JButton applyButton;
	private javax.swing.JButton cancelButton;
	private javax.swing.JCheckBox jCheckBox1;
	private javax.swing.JCheckBox jCheckBox2;
	private javax.swing.JCheckBox jCheckBox3;
	private javax.swing.JCheckBox jCheckBox4;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel18;
	private javax.swing.JLabel jLabel19;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel10;
	private javax.swing.JPanel jPanel11;
	private javax.swing.JPanel jPanel12;
	private javax.swing.JPanel jPanel13;
	private javax.swing.JPanel jPanel14;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JPanel jPanel7;
	private javax.swing.JPanel jPanel8;
	private javax.swing.JPanel jPanel9;
	private javax.swing.JSpinner jSpinner1;
	private javax.swing.JSpinner jSpinner2;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField10;
	private javax.swing.JTextField jTextField11;
	private javax.swing.JTextField jTextField12;
	private javax.swing.JTextField jTextField13;
	private javax.swing.JTextField jTextField14;
	private javax.swing.JTextField jTextField15;
	private javax.swing.JTextField jTextField16;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	private javax.swing.JTextField jTextField5;
	private javax.swing.JTextField jTextField6;
	private javax.swing.JTextField jTextField7;
	private javax.swing.JTextField jTextField8;
	private javax.swing.JTextField jTextField9;
	private javax.swing.JButton okButton;
	private javax.swing.JCheckBox perigeeCheckBox;
	private javax.swing.JTabbedPane propTabbedPane;

	// End of variables declaration//GEN-END:variables

	private boolean saveSettings() {
		// save settings back to Node
		boolean saveSuccess = true;

		try {

			pNode.setStopOnPerigee(perigeeCheckBox.isSelected());
			pNode.setStopOnApogee(apogeeCheckBox.isSelected());

			// Display settings
			pNode.setStepSize(Double.parseDouble(jTextField5.getText()));

			pNode.setPopogateTimeLen(Double.parseDouble(jTextField9.getText()));

			// Wich propagation model
			pNode.setPropogator(propTabbedPane.getSelectedIndex());

			switch (propTabbedPane.getSelectedIndex()) {

			// Numerical
			case 0:
				// fill in fields with saved values
				pNode.setN_max((Integer) jSpinner1.getValue());
				pNode.setM_max((Integer) jSpinner2.getValue());

				pNode.setIncludeLunarPert(jCheckBox1.isSelected());
				pNode.setIncludeSunPert(jCheckBox2.isSelected());
				pNode.setIncludeSolRadPress(jCheckBox3.isSelected());
				pNode.setIncludeAtmosDrag(jCheckBox4.isSelected());

				pNode.setMass(Double.parseDouble(jTextField1.getText()));
				pNode.setArea(Double.parseDouble(jTextField2.getText()));
				pNode.setCR(Double.parseDouble(jTextField3.getText()));
				pNode.setCD(Double.parseDouble(jTextField4.getText()));

				// Hprop-7/8 only if needed
				// if(inputComboBox2.getSelectedIndex() ==
				// PropogatorNode.HPROP78)
				// {
				pNode.setMaxStepSize(Double.parseDouble(jTextField6.getText()));
				pNode.setMinStepSize(Double.parseDouble(jTextField7.getText()));
				pNode.setRelAccuracy(Double.parseDouble(jTextField8.getText()));

				// }
				break;

			case 1:
				// Keplerian
				pNode.setMu(Double.parseDouble(jTextField10.getText()));
				break;

			case 2:
				// Eckstein Hechler
				pNode.setMu(Double.parseDouble(jTextField11.getText()));

				// Un-normalized zonal coefficient
				pNode.setZonalCoefficients(
						Double.parseDouble(jTextField12.getText()),
						Double.parseDouble(jTextField13.getText()),
						Double.parseDouble(jTextField14.getText()),
						Double.parseDouble(jTextField15.getText()),
						Double.parseDouble(jTextField16.getText()));

				break;

			case 3:
				// Semi-analytical
				// Not implemented yet

				JOptionPane.showMessageDialog(this, "Not implemented yet",
						"Warning", JOptionPane.WARNING_MESSAGE);
				break;

			default:
				break;

			}

		} catch (Exception e) {
			JOptionPane.showMessageDialog(this,
					"Date format error, check input.", "Data ERROR",
					JOptionPane.ERROR_MESSAGE);
			saveSuccess = false;
		}

		return saveSuccess;

	} // save settings
}
